# Copyright 2023 DeepMind Technologies Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================

"""Class for evaluating programs proposed by the Sampler."""
from __future__ import annotations

from abc import abstractmethod, ABC
import ast
import dataclasses
import time
from collections.abc import Sequence
import copy
from typing import Any, Type
import profile

from implementation import code_manipulation
from implementation import programs_database


@dataclasses.dataclass
class EvalResult:
    """Structured evaluation feedback returned by Evaluator.analyse()."""
    function: code_manipulation.Function | None
    program: str
    scores_per_test: dict
    reduced_score: float | None
    error_trace: str | None
    is_valid: bool
    registered: bool


def _reduce_score(scores_per_test: dict) -> float | None:
    if not scores_per_test:
        return None
    values = list(scores_per_test.values())
    return sum(values) / len(values)


class _FunctionLineVisitor(ast.NodeVisitor):
    """Visitor that finds the last line number of a function with a given name."""

    def __init__(self, target_function_name: str) -> None:
        self._target_function_name: str = target_function_name
        self._function_end_line: int | None = None

    def visit_FunctionDef(self, node: Any) -> None:  # pylint: disable=invalid-name
        """Collects the end line number of the target function."""
        if node.name == self._target_function_name:
            self._function_end_line = node.end_lineno
        self.generic_visit(node)

    @property
    def function_end_line(self) -> int:
        """Line number of the final line of function `target_function_name`."""
        assert self._function_end_line is not None
        return self._function_end_line


def _trim_function_body(generated_code: str) -> str:
    """Extracts the body of the generated function, trimming anything after it."""
    if not generated_code:
        return ''

    code = f'def fake_function_header():\n{generated_code}'

    tree = None
    while tree is None:
        try:
            tree = ast.parse(code)
        except SyntaxError as e:
            code = '\n'.join(code.splitlines()[:e.lineno - 1])

    if not code:
        return ''

    visitor = _FunctionLineVisitor('fake_function_header')
    visitor.visit(tree)
    body_lines = code.splitlines()[1:visitor.function_end_line]
    return '\n'.join(body_lines) + '\n\n'


def _sample_to_program(
        generated_code: str,
        version_generated: int | None,
        template: code_manipulation.Program,
        function_to_evolve: str,
) -> tuple[code_manipulation.Function, str]:
    """Returns the compiled generated function and the full runnable program."""
    body = _trim_function_body(generated_code)
    if version_generated is not None:
        body = code_manipulation.rename_function_calls(
            code=body,
            source_name=f'{function_to_evolve}_v{version_generated}',
            target_name=function_to_evolve
        )

    program = copy.deepcopy(template)
    evolved_function = program.get_function(function_to_evolve)
    evolved_function.body = body
    return evolved_function, str(program)


class Sandbox(ABC):
    """Sandbox for executing generated code."""

    @abstractmethod
    def run(
            self,
            program: str,
            function_to_run: str,
            function_to_evolve: str,
            inputs: Any,
            test_input: str,
            timeout_seconds: int,
            **kwargs
    ) -> tuple[Any, bool, str | None]:
        """Returns (result, success, error_message).

        The third element is the error trace string when execution fails,
        or None on success.
        """
        raise NotImplementedError(
            'Must provide a sandbox for executing untrusted code.')


def _calls_ancestor(program: str, function_to_evolve: str) -> bool:
    """Returns whether the generated function is calling an earlier version."""
    for name in code_manipulation.get_functions_called(program):
        if name.startswith(f'{function_to_evolve}_v'):
            return True
    return False


class Evaluator:
    """Class that analyses functions generated by LLMs."""

    def __init__(
            self,
            database: programs_database.ProgramsDatabase,
            template: code_manipulation.Program,
            function_to_evolve: str,
            function_to_run: str,
            inputs: Sequence[Any],
            timeout_seconds: int = 30,
            sandbox_class: Type[Sandbox] = Sandbox
    ):
        self._database = database
        self._template = template
        self._function_to_evolve = function_to_evolve
        self._function_to_run = function_to_run
        self._inputs = inputs
        self._timeout_seconds = timeout_seconds
        self._sandbox = sandbox_class()

    def analyse(
            self,
            sample: str,
            island_id: int | None,
            version_generated: int | None,
            thought: str | None = None,
            **kwargs
    ) -> EvalResult:
        """Compiles the sample into a program and executes it on test inputs.

        Returns an EvalResult with scores, error traces, and registration status.
        """
        new_function, program = _sample_to_program(
            sample, version_generated, self._template, self._function_to_evolve)
        if thought is not None:
            new_function.thought = thought
        scores_per_test = {}
        collected_errors: list[str] = []

        time_reset = time.time()
        for current_input in self._inputs:
            result = self._sandbox.run(
                program, self._function_to_run, self._function_to_evolve,
                self._inputs, current_input, self._timeout_seconds
            )
            # Support both old (2-tuple) and new (3-tuple) Sandbox return format
            if len(result) == 3:
                test_output, runs_ok, error_msg = result
            else:
                test_output, runs_ok = result
                error_msg = None

            if error_msg:
                collected_errors.append(f"[{current_input}] {error_msg}")

            if (runs_ok
                    and not _calls_ancestor(program, self._function_to_evolve)
                    and test_output is not None):
                if not isinstance(test_output, (int, float)):
                    collected_errors.append(
                        f"[{current_input}] function.run returned non-numeric: {test_output}")
                    continue
                scores_per_test[current_input] = test_output

        evaluate_time = time.time() - time_reset
        reduced_score = _reduce_score(scores_per_test)
        error_trace = '\n'.join(collected_errors) if collected_errors else None
        is_valid = bool(scores_per_test)
        registered = False

        if scores_per_test:
            self._database.register_program(
                new_function,
                island_id,
                scores_per_test,
                **kwargs,
                evaluate_time=evaluate_time
            )
            registered = True
        else:
            profiler: profile.Profiler = kwargs.get('profiler', None)
            if profiler:
                global_sample_nums = kwargs.get('global_sample_nums', None)
                sample_time = kwargs.get('sample_time', None)
                new_function.global_sample_nums = global_sample_nums
                new_function.score = None
                new_function.sample_time = sample_time
                new_function.evaluate_time = evaluate_time
                profiler.register_function(new_function)

        return EvalResult(
            function=new_function,
            program=program,
            scores_per_test=scores_per_test,
            reduced_score=reduced_score,
            error_trace=error_trace,
            is_valid=is_valid,
            registered=registered,
        )
